# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/ASUS/AppData/Roaming/Xilinx/Vivado/Desktop/finalProjMai2/finalProjMai2.cache/wt [current_project]
set_property parent.project_path C:/Users/ASUS/AppData/Roaming/Xilinx/Vivado/Desktop/finalProjMai2/finalProjMai2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property vhdl_version vhdl_2k [current_fileset]
add_files C:/Users/ASUS/Downloads/sprite_rom.coe
add_files -quiet C:/Users/ASUS/AppData/Roaming/Xilinx/Vivado/Desktop/finalProjMai2/finalProjMai2.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp
set_property used_in_implementation false [get_files C:/Users/ASUS/AppData/Roaming/Xilinx/Vivado/Desktop/finalProjMai2/finalProjMai2.runs/blk_mem_gen_0_synth_1/blk_mem_gen_0.dcp]
add_files -quiet C:/Users/ASUS/AppData/Roaming/Xilinx/Vivado/Desktop/finalProjMai2/finalProjMai2.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp
set_property used_in_implementation false [get_files C:/Users/ASUS/AppData/Roaming/Xilinx/Vivado/Desktop/finalProjMai2/finalProjMai2.runs/blk_mem_gen_1_synth_1/blk_mem_gen_1.dcp]
read_verilog -library xil_defaultlib {
  C:/Users/ASUS/AppData/Roaming/Xilinx/Vivado/Desktop/finalProjMai2/finalProjMai2.srcs/sources_1/new/vga.v
  C:/Users/ASUS/AppData/Roaming/Xilinx/Vivado/Desktop/finalProjMai2/finalProjMai2.srcs/sources_1/new/top.v
}
read_xdc C:/Users/ASUS/AppData/Roaming/Xilinx/Vivado/Desktop/finalProjMai2/finalProjMai2.srcs/constrs_1/new/const.xdc
set_property used_in_implementation false [get_files C:/Users/ASUS/AppData/Roaming/Xilinx/Vivado/Desktop/finalProjMai2/finalProjMai2.srcs/constrs_1/new/const.xdc]

synth_design -top top_module -part xc7a35tcpg236-1
write_checkpoint -noxdef top_module.dcp
catch { report_utilization -file top_module_utilization_synth.rpt -pb top_module_utilization_synth.pb }
